LDFLAGS=-std=c++11

testPlayer: ;  g++ $(LDFLAGS) Archer.cpp Board.cpp Fighter.cpp Game.cpp InputParser.cpp Player.cpp Priest.cpp Scout.cpp Tank.cpp testPlayer.cpp -o testPlayer -g

testBoard: ; g++ $(LDFLAGS) Archer.cpp Board.cpp Fighter.cpp Game.cpp InputParser.cpp Player.cpp Priest.cpp Scout.cpp Tank.cpp testBoard.cpp -o testBoard -g 
testGame: ;g++ $(LDFLAGS) Archer.cpp Board.cpp Fighter.cpp Game.cpp InputParser.cpp Player.cpp Priest.cpp Scout.cpp Tank.cpp testGame.cpp -o testGame -g
clean: ;  rm testGame;
