rasterizer_cpp:
	g++ -Wall -g -std=c++11 Vec3.cpp Vec4.cpp Triangle.cpp Matrix4.cpp Color.cpp Camera.cpp tinyxml2.cpp Scaling.cpp Rotation.cpp Translation.cpp Model.cpp Helpers.cpp Scene.cpp Main.cpp -o rasterizer

clean:
	rm -rf *.ppm *.png ./rasterizer